### ISSUE TITLE
[Summary] toolchain release v1.0 todo list

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph-toolchain#340]
## High Priority (高优先级)

- [ ] fix license & binary issue
     - [ ] remove binary test file & download them #425 
     - [ ] fix 3rd party code refer problems #426 
     - [ ] check if there are any `GPL/CC` license & better to add a action/ci for it
- [ ] support hubble dockerfile 
- [x] binary package inspection, description, signature
- [x] adapt the latest server version V1.0
- [x]  add license head for hubble-fe (idea's `Update CopyRight` function and check with rat plugi)
- [x] fix hubble bug #377 
- [x] fix loader's spark jackson problem
- [x]  #339 @imbajin
- [x]  #336  @simon824 
- [x]  #338 @simon824 
- [x]  Check the licenses of all dependent third-party libraries
  - [x] Find all the dependent license/NOTICE files (unzip the jar package or go to the source code repository) and copy them to the licenses directory of the toolchains repository (refer to the [link](https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-dist/release-docs))
  - [x]  Check whether the license conflicts with Apache2.0
- [x] old pr review & merge ---- @javeme @imbajin @zyxxoo @coderzc etc.

## Normal Priority (中优先级)

- [x]  rename `com.baidu` to `org.apache` and adjust the package style  #366
  - [x]  loader module
  - [x]  tools module
  - [x]  client module
  - [x]  hubble module

## Low Priority (低优先级)
- [ ] CVE security check & fix the code/dependencies problem
- [x]  add rat ci @JackyYangPassion 
- [x] clean the code (refer [PR](https://github.com/apache/incubator-hugegraph-commons/pull/110/files))
- [x] fix the auth error in client's test (now just ignore it)

**Comment by imbajin** [comment]
we could separate the TODOs in each repository (and link them to `Projects`), will be more clearly

**Comment by JackyYangPassion** [comment]
i can try "add rat ci"   @simon824 @imbajin

**Comment by JackyYangPassion** [comment]
#352  for client model
