### ISSUE TITLE
[Enhancement] Unify & clean code style in hubble & client

### ISSUE THREAD

**Issue by returnToInnocence** [apache/incubator-hugegraph-toolchain#591]
# SubTask

**PS:**  Since the changes and logic involved are not complex, it is done in one PR according to the way different subtasks commit

- [ ] hubble-be format & clean task
	- [ ] Correct the copyright format.
		- [ ] `.py` copyright formatting standards need further discussion
			This is due to the `File | Settings | Editor | Code Style` in IDEA does not include the python files
			My personal thoughts (refer to **apache-airflow**), copyright and `.editorconfig`:
				1. indent_size = 4
				2. max_line_length = 110
				3. copyright style in `.py` may looks like [apache-airflow's python file](https://github.com/apache/airflow/blob/main/airflow/api/auth/backend/basic_auth.py)
		- [x] other files
	- [ ] Format the hubble-be module
		- [x] File type `.java`
		- [x] File type `.xml`
		- [x] File type `.properties`
		- [ ]  `.py` formatting standards need further discussion
			This is due to the `File | Settings | Editor | Copyright | Formatting` in IDEA does not include the python files
	- [x] Clean up the code. 

- [ ] hubble-fe format & clean task
	- [ ] Formatting standards may require further investigation and discussion

- [x] client format & clean task
- [x] loader format & clean task
- [x] spark-connector format & clean task
- [x] tools format & clean task

## Related PR
1. #592
